### ISSUE TITLE
Windows startup with GUI Counter

### ISSUE THREAD

**Issue by T-wcs** [T-wcs/RansomPy-Covid19#1]
It's appears is a incorrectly values into db.txt to the " PerfLogs\gui_counter " directory, who permetly normaly to set update the counter time

Error message : 
File "gui_counter", line 60, in <modules>
ValueError: invalid literal for int() with base 10:
 "\x00\x00\x00\x00\x00\x00\x00\x00\x00"

Picture : 
![Bug_Gui_After_Restart_Windows](https://user-images.githubusercontent.com/70718793/97783657-8ded0880-1b99-11eb-95ef-04d66bc32fe1.png)

Into db.txt (after restart the system):
![Into_db_txt](https://user-images.githubusercontent.com/70718793/97783695-c55bb500-1b99-11eb-9329-a133b17e1573.png)

**Comment by T-wcs** [comment]
The issue was solved with the method try and except into the gui counter code

**Comment by T-wcs** [comment]
![image](https://user-images.githubusercontent.com/70718793/97788240-d6b3ba00-1bb7-11eb-8b48-6bc78d6a8e30.png)


if the values is incorrect also the new value of the counter is set in the timer (12hours), the code consider the computer was restarted on emergency

**Comment by ThomasPoirier-CS** [comment]
if the values is incorrect also the new value of the counter is set in the timer (12hours), the code consider the computer was restarted on emergency
